"""
AuraBot — Inline Mode
Inline music search, sticker generation, waifu lookup, and GIF reactions.
"""

from __future__ import annotations

import asyncio
import uuid
from typing import List

from pyrogram import Client, filters
from pyrogram.types import (
    InlineQuery,
    InlineQueryResultArticle,
    InlineQueryResultAnimation,
    InlineQueryResultPhoto,
    InputTextMessageContent,
)

from config import cfg
from core.logger import get_logger
from music.extractor import extractor
from plugins.anime.waifu import fetch_anime_image

log = get_logger("inline")


def inline_router(app: Client) -> None:

    @app.on_inline_query()
    async def handle_inline(client: Client, query: InlineQuery) -> None:
        q = query.query.strip().lower()

        if not q:
            await query.answer(
                results=_default_results(),
                cache_time=10,
                is_gallery=False,
            )
            return

        # Dispatch by prefix
        if q.startswith("s "):
            # Sticker generation inline
            await _handle_sticker_inline(query, q[2:].strip())
        elif q.startswith("w ") or q.startswith("waifu"):
            # Waifu GIF
            await _handle_waifu_inline(query, q)
        elif q.startswith("hug ") or q.startswith("kiss ") or q.startswith("pat "):
            action = q.split(" ", 1)[0]
            await _handle_reaction_inline(query, action)
        else:
            # Default: music search
            await _handle_music_inline(query, q)


async def _handle_music_inline(query: InlineQuery, search: str) -> None:
    try:
        track = await asyncio.wait_for(
            extractor.resolve(search, user_id=query.from_user.id),
            timeout=8.0,
        )
    except asyncio.TimeoutError:
        track = None

    if not track:
        await query.answer(
            results=[
                InlineQueryResultArticle(
                    id=str(uuid.uuid4()),
                    title="❌ No results found",
                    description=f'No tracks found for "{search}"',
                    input_message_content=InputTextMessageContent(
                        f"🔍 Searching for: {search}"
                    ),
                )
            ],
            cache_time=5,
        )
        return

    result = InlineQueryResultArticle(
        id=str(uuid.uuid4()),
        title=f"🎵 {track.title}",
        description=(
            f"👤 {track.artist or 'Unknown'} • ⏱ {track.duration_str} • {track.source}"
        ),
        input_message_content=InputTextMessageContent(
            f"🎵 **{track.title}**\n"
            f"👤 {track.artist or 'Unknown'}\n"
            f"⏱ {track.duration_str}\n"
            f"📡 {track.source.title()}"
        ),
        thumb_url=track.thumbnail,
    )
    await query.answer(results=[result], cache_time=30)


async def _handle_waifu_inline(query: InlineQuery, q: str) -> None:
    url = await fetch_anime_image("waifu")
    if not url:
        return
    result = InlineQueryResultPhoto(
        id=str(uuid.uuid4()),
        photo_url=url,
        thumb_url=url,
        caption="🌸 Waifu rolled inline!",
    )
    await query.answer(results=[result], cache_time=0)


async def _handle_reaction_inline(query: InlineQuery, action: str) -> None:
    url = await fetch_anime_image(action)
    if not url:
        return
    result = InlineQueryResultAnimation(
        id=str(uuid.uuid4()),
        animation_url=url,
        thumb_url=url,
        caption=f"_{action.capitalize()} from inline!_",
    )
    await query.answer(results=[result], cache_time=10)


async def _handle_sticker_inline(query: InlineQuery, text: str) -> None:
    if not text:
        return
    # For inline we return a preview article (sticker generation is server-side)
    result = InlineQueryResultArticle(
        id=str(uuid.uuid4()),
        title=f"✨ Create sticker: {text[:30]}",
        description="Tap to send — sticker will be generated by bot",
        input_message_content=InputTextMessageContent(
            f"/s {text}"
        ),
    )
    await query.answer(results=[result], cache_time=0)


def _default_results() -> list:
    return [
        InlineQueryResultArticle(
            id="help_music",
            title="🎵 Search Music",
            description="Type a song name or YouTube URL",
            input_message_content=InputTextMessageContent("🎵 Use inline to search music!"),
        ),
        InlineQueryResultArticle(
            id="help_sticker",
            title="✨ Create Sticker",
            description='Type "s your text here"',
            input_message_content=InputTextMessageContent("✨ Use inline to create stickers!"),
        ),
        InlineQueryResultArticle(
            id="help_waifu",
            title="🌸 Get Waifu",
            description='Type "waifu" or "w anime"',
            input_message_content=InputTextMessageContent("🌸 Use inline to get a waifu!"),
        ),
    ]
